### ISSUE TITLE
Overriding validation of UserStoreCrudRequest

### ISSUE THREAD

**Issue by radvc** [Laravel-Backpack/PermissionManager#100]
Hi, im having a big problem right now in my laravel app with backpack and permission manager, I want to override the validation for creating users, when I override the store method from my own controller I've got an error:

` Declaration of App\Http\Controllers\Admin\UserCrudController::store() should be compatible with Backpack\PermissionManager\app\Http\Controllers\UserCrudController::store(Backpack\PermissionManager\app\Http\Requests\UserStoreCrudRequest $request)`

**Comment by lloy0076** [comment]
What's your store method declaration look like and specifically how have you setup the request?

(This has happened to other but I can't remember what the solution is off the top of my head)

NB. This isn't a bug nor is it really Backpack - it's PHP being grumpy..

**Comment by teejei** [comment]
@radvc try to use Illuminate\Http\Request instead of App\Http\Requests\Request,

**Comment by AbbyJanke** [comment]
You also need to define the variables with the function name:

`Backpack\PermissionManager\app\Http\Requests\UserStoreCrudRequest $request` needs to be there as well.

**Comment by radvc** [comment]
thank you guys but my one of our team fix the problem, I didnt ask him how he do it.

**Comment by abdelrahmanahmed** [comment]
@radvc could you ask him how did he do it because I have the issue right now.

**Comment by teejei** [comment]
@abdelrahmanahmed replace App\Http\Requests\Request to  Illuminate\Http\Request at your controller.

**Comment by gasparyanyur** [comment]
Same error when trying to overwrite update function.

Here is my custom request:

namespace App\Http\Requests;

use Illuminate\Http\Request;

```
class UserCrudRequest extends Request
{
    public function rules()
    {
        return [
            'fname' => 'required|min:3|max:50',
            'lname' => 'required|min:3|max:50',
            'mname' => 'required|min:3|max:50',
        ];
    }
}
```

In `controller` I have overwrite `update` function look like this

    ```
public function update(UserCrudRequest $request)
    {
        return parent::update($request); // TODO: Change the autogenerated stub
    }
```

**Comment by lj3lj3** [comment]
Same here, does anyone got a solution?

**Comment by AhmedAmshir** [comment]
I have the same issue, does anyone got a solution?

**Comment by roberttolton** [comment]
Looking for a solution for this too!

**Comment by ariaenggar** [comment]
still no solution?

**Comment by budiprasetyo** [comment]
I think it was clearly stated by @lloy0076 , opening issues here only related with bugs or something like proposing new features.  The problem like that, you can try to ask on [https://stackoverflow.com/](url)

**Comment by tabacitu** [comment]
Quick heads-up: in Backpack v4 this should no longer be a problem, since create&update no longer use type-hinting for validation. The process, though, should be the same as [the note in the readme file on overwriting functionality](https://github.com/Laravel-Backpack/PermissionManager#overwriting-functionality):
- create a ```permissionmanager.php``` route file, and point the ```user``` route to a new ```UserCrudController``` you create;
- make sure that ```UserCrudController``` extends the one in the package, and only overwrite the operations you need (in this case the Create and Update operations, to use a new FormRequest file);
- create a new UserRequest where you specify your custom validation;

Notes:
- since this overwrites a lot of the operations, you could choose to include all operation code in your new controller and not extend the controller from the package; that's ok too;
- instead of using a FormRequest for validation, you could also use the standard Laravel validator class;

Hope it helps someone.
Cheers!
