### ISSUE TITLE
request: add role/permission validation on admin part

### ISSUE THREAD

**Issue by kruisdraad** [Laravel-Backpack/PermissionManager#105]
Would you consider adding a config item that allows to enable a default role to protect the admin middleware easily.

I have this by:

vendor/backpack/base/src/app/Http/Middleware/Admin.php

Adding [21:23}

```
        if (!Auth::User()->hasRole('Administrators')) {
            return redirect()->guest(config('backpack.base.route_prefix', 'admin').'/login');
        }
```

This hardcodes it, but wrapping it in something like:

```
if (config('backpack.base.route_role) !== false) {
        if (!Auth::User()->hasRole(config('backpack.base.route_role))) {
            return redirect()->guest(config('backpack.base.route_prefix', 'admin').'/login');
        }
}
```

In the base you can set this to false. You can even add another IF clause checking if the permission manager is even installed

**Comment by hassan848** [comment]
Yes this should be implemented, and it should be implemented to the optional backpack packages as well.

**Comment by lloy0076** [comment]
This is a valid request for enhancement but I think that there is a fix in base or "somewhere else" and it already has a PR (although various contributors are still discussing exactly how the fix should work).

I won't close for the moment.

**Comment by tabacitu** [comment]
Hi guys,

Thank you for the suggestion @kruisdraad . I agree with you, this should be easier. That's why [the new Backpack/Base version bump](https://github.com/Laravel-Backpack/Base/pull/259) (0.9.0, due later this week) will have a solution for this. The "admin" middleware will actually be a middleware group, and you can easily add stuff to it in the ```config/backpack/base.php``` file.

So I'm going to close this. Reopen if it's not a good solution.
Cheers!
