### ISSUE TITLE
Is there any "Admin" generic role?

### ISSUE THREAD

**Issue by elfeffe** [Laravel-Backpack/PermissionManager#11]
I just can't find if there is any "Admin" role that can access everything by default, or if the solution is to check it everytime.
My plan is to check if user has permission, or is admin. But is something already made for admin?

**Comment by tabacitu** [comment]
Hi @elfeffe ,

Right now there are no roles or permissions provided by default - those tables come empty. So you need to code your own checks. 

I don't know your application, but I bet the sexiest way to do that would be using a middleware. That way, you'll do the actual check in the route file, instead of in the controllers, each time. I _think_ you can overwrite the [Admin middleware from Backpack\Base](https://github.com/Laravel-Backpack/Base/blob/master/src/app/Http/Middleware/Admin.php) by 
1) creating a new file in your project (app/Http/Middleware/Admin.php);
2) [placing it under the 'admin' alias in the Kernel.php file](https://laravel.com/docs/5.2/middleware#registering-middleware);
3) in your handle() method, also performing a check to see if the logged in user is an admin;

That being said, I don't know if this is the best way to handle users, roles and permissions in your application. If it's a medium/big app, and the specs might change in time, perhaps a more forward-thinking way of handling it would be to use the permissions for checks, and the roles only as a way to separate permissions between users. 
- If you have a permission for each thing that can be done in the application, you can check for those instead of roles; When things chagne, just assign in the admin panel to the right role or user. 
- If you code checks to the user, but also code checks to the permissions, this can quickly become unmanageable. 

--

You do bring up a good question, though. If someone installs Backpack\PermissionManager, they most likely need at least 2 roles - admin and regular user. Otherwise they wouldn't have installed this package. It would be faster to the developer if we already provide middleware for those two. Easiest way to do that is by:
1) having two roles in the db: admin, user; still no permissions;
2) having an extra middleware: admin (which overwrites the one from the Backpack\Base package) and also checks for the role;
@mariusconstantin2503 @cristiantone @Ghitu what do you think? My big question is wether this will push people towards a bad practice - checking for the role, instead of creating a permission for everything and checking for that.

**Comment by elfeffe** [comment]
Thank you, I will check.

My way was adding Admin role and then

` @hasrole(['Export Editor', 'Admin'])`

**Comment by tabacitu** [comment]
Yup, that's exactly what I thought. It's ok to do it that way, I guess. It will work. But I prefer to test permissions instead of roles.

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by cdarken** [comment]
@tabacitu overriding the middleware by registering it with the same name in the app Kernel class doesn't work, it's ignored
