### ISSUE TITLE
Array to string conversion Error in UserCrudController during the store/update process

### ISSUE THREAD

**Issue by Mortred974** [Laravel-Backpack/PermissionManager#126]
Hi ! 

I've overwritten the UserCrudController in order to add my own fields/validation process.

I've notice that i can't update/store a user, cause of Array to string conversion error.

Can you confirm this issue ?

I guess the problem is due to of `roles_show`and `permissions_show` fields.

I add this to the `UserCrudController.php` (my custom one) :  
```
public function store(StoreRequest $request)
    {
        $this->handlePasswordInput($request);

        // Fix : remove unfillable fields in order to avoid `Array to string conversion` error ? 
        $request->request->remove('roles_show');
        $request->request->remove('permissions_show');

        return parent::storeCrud($request);
    }
    ...
public function update(UpdateRequest $request)
    {
        $this->handlePasswordInput($request);

        // Fix : remove unfillable fields in order to avoid `Array to string conversion` error ? 
        $request->request->remove('roles_show');
        $request->request->remove('permissions_show');

        return parent::updateCrud($request);
    }
```

With that fix, it seems to work.

Maybe could you do this in a better way ? Or add a PR for this ?

Note : 
* Maybe we can fill the  `$fillable` of the User model, but i prefer keep the `$guarded` process :).
* even if i use the original UserCrudController, the same error is throwed.

**Comment by cthiele-mogic** [comment]
Same error for me!

**Comment by cthiele-mogic** [comment]
The checkbox name="roles_show[]"  ( Role-Permission Form in User Detail View) should not be transfered to the controller or the controller must exclude this variable (like in the fix from @Mortred974 )

**Comment by tabacitu** [comment]
Hi @Mortred974 - thanks for documenting this. Should help other people overwriting the UserCrudController, when they find this.

Cheers!

**Comment by ziming** [comment]
Hi @tabacitu, any reason why a patch for this is not made? How would you recommend overriding this?

**Comment by tabacitu** [comment]
Hi @ziming - I got no problems when overwriting the controller in the package - I just assumed the OP had issues because of his own code, since the ```roles_show``` and ```permissions_show``` fields he mentioned do not exist in the package. The only difference when I extend is that I call ```parent::store()``` which itself calls ```parent::storeCrud()``` - that way the password is also handled. So it's:

```php
public function store(StoreRequest $request)
    {
        return parent::store($request);
    }

public function update(UpdateRequest $request)
    {
        return parent::update($request);
    }
```

**Comment by tabacitu** [comment]
Hi @ziming - thank you for surfacing this. I thought it was user error - since I didn't see ```roles_show``` and ```permission_show``` as fields, I thought the OP added them. Now I understand they're part of the ```checklist_dependency``` field type, saw your PR, and will be merging it. Thanks a lot for bringing this up, and especially for taking the time to put together the PR.

Cheers!
