### ISSUE TITLE
UserCrudController store QueryException

### ISSUE THREAD

**Issue by Darival** [Laravel-Backpack/PermissionManager#15]
In `Backpack\PermissionManager\app\Http\Controllers\UserCrudController` line 117 ([Halo reference)](http://vignette3.wikia.nocookie.net/halo/images/b/b1/H2A_CinematicRender_John-117-CloseFrontView.jpg/revision/latest?cb=20141220010105)
```php
$item = $this->crud->create(\Request::except(['redirect_after_save', 'password']));
```
returns
`
 General error: 1364 Field 'password' doesn't have a default value (SQL: insert into `users` (`name`, `email`, `updated_at`, `created_at`) values (test, test@testing.com, 2016-09-07 06:02:00, 2016-09-07 06:02:00))
`
looks like It can not create an instance of user without password

**Comment by tabacitu** [comment]
:-)) Ugh. This is because Laravel 5.3 ships with MySQL "strict" mode on by default. This needs to be adressed - check everything so that it works with strict on, so I'll leave the ticket open until we do that.

But in the meantime, you can set "strict" to false in your ```config/database.php``` file, for the mysql configuration - that should fix it. 

Cheers!

**Comment by tabacitu** [comment]
I've just pushed an update to both CRUD and PermissionManager that fixes the MySQL strict issue. We can now use MySQL strict=true in Backpack.

Cheers!
