### ISSUE TITLE
Composer Update breaks PermissionManager

### ISSUE THREAD

**Issue by tekhoi** [Laravel-Backpack/PermissionManager#156]
This evening I ran Composer Update

Package operations: 0 installs, 2 updates, 0 removals
  - Updating spatie/laravel-permission (1.16.1 => 2.12.1): Downloading (100%)
  - Updating backpack/permissionmanager (2.1.27 => 2.12.0): Downloading (100%)
  
The major upgrade to spatie/laravel-permission caused many errors.

Shouldn't it be that a breaking update requires composer.json to be updated and not auto updated?

For now I have fixed backpack/permissionmanager to version 2.1.27

The suggestions seem to be that V1 should be removed and V2 installed from scratch.
https://github.com/spatie/laravel-permission/issues/262

**Comment by AbbyJanke** [comment]
Hello @tekhoi 

Typically when you run "composer require PACKAGENAME" it installs such as:

```
"backpack/permissionmanager": "^2.1",
```

The `^` within the version number means that it will install any version equal to our greater then 2.1. I always recommend on production environments you hard set the version number and leave the `^` for development and testing environments. When @tabacitu merged the PR to upgrade it, he was aware there may be some breaking changes but it was a necessary update as our version of `spatie/laravel-permission` was super outdatted.

**Comment by tabacitu** [comment]
Hi @tekhoi , @AbbyJanke ,

Thanks a lot for this. I think you're both right. Yes, we bumped the minor version but if ```composer update``` breaks people's apps, I made a big mistake, and might have broken hundreds of people's apps... I thought composer uses ```"^2.1.0"``` by default (notice the patch number). 

**I've just deleted that version (```2.12.0```) and pushed it as ```3.12.0``` so that we're 100% sure it doesn't break people's apps, and people need to install it separately in order to work.**

@tekhoi you should be able to run ```composer update``` again and it'll be fixed, it should pull in permissionmanager 2.1.27. If not, please run ```composer require backpack/permissionmanager 2.1.27```.

Cheers!

PS. For those who have installed permissionmanager correctly in the meantime, on a new project, and have version ``` 2.12.0``` installed, please change it in your composer.json to ```3.12.0``` and run ```composer update```.

**Comment by tekhoi** [comment]
@tabacitu thanks for the extra update.

composer update is still updating to version 2.12.0, I have fixed the version in composer.json (so all fine now) until I have time to update spatie/laravel-permission to 2.x  (which I will be doing ASAP)

Just wanted to let you know in case anyone else has this issue.

Package operations: 0 installs, 2 updates, 0 removals
  - Updating spatie/laravel-permission (1.16.1 => 2.12.1): Downloading (100%)
  - Updating backpack/permissionmanager (2.1.27 => 2.12.0): Downloading (100%)

composer require backpack/permissionmanager 2.1.27 also caused problems for me as this app is using Laravel 5.5 and with this command spatie/laravel-permission then requires Laravel 5.4 or lower

**Comment by tabacitu** [comment]
You're totally right @tekhoi . Thank you, I just deleted it from Packagist too. Looks like it doesn't automatically pick up tag deletions from Github - didn't know that.

Thanks again, cheers!
