### ISSUE TITLE
Will there ever be a Bouncer Permission Manager?

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/PermissionManager#163]
More of a question/new feature request.

The permission manager is based on spatie permissions which is great. But my team chose Bouncer for it's extra flexibility.

We can build the CRUD for it ourselves too but just wondering if you guys are planning  ona Permission Manager based on Bouncer one in the future since it's 1 of the 2 most laravel permissions related packages and include features like multi-tenancy permission support and the fallback to ModelPolicy methods if the permission isn't found in the database

https://github.com/JosephSilber/bouncer

**Comment by tabacitu** [comment]
@ziming - no, no support for Bouncer is planned yet. 

I would _totally_ support a new package that brings this to Backpack, though, in any way I can. I would love to see more small packages, from third parties, that create an admin panel for broad use cases like this. 

If you do decide to build one, consider making it a package instead. It isn't too difficult ([tutorial here](https://medium.com/@tabacitu/creating-laravel-5-packages-for-dummies-ec6a4ded2e93?source=user_profile---------3-------------------)) and you would probably be helping a lot of people out, make your name stand out and make a few friends :-) I don't recommend creating a bunch of packages in a short time, like I did, though, because maintenance is a b#7ch :-) But one package, totally fun to build and launch. If so, let me know at hello@tabacitu.ro - happy to help you get feedback and promote it.

Cheers!
