### ISSUE TITLE
Method Illuminate\Database\Query\Builder::hasAnyPermissions does not exist.

### ISSUE THREAD

**Issue by swingywc** [Laravel-Backpack/PermissionManager#164]
As in `spatie/laravel-permission`, they have a method called `->hasAnyPermissions(array())`. I would like to use it in this package but this method is not yet exist.

I would like to ask if we can implement this method also? Appreciate for any kindly help.

**Comment by tabacitu** [comment]
Hi @swingywc ,

Sorry for the late reply. This package is just a wrapper, a visual interface over spatie/laravel-permission - so whatever it has, this has, because you're _actually using_ spatie/laravel-permission.

If you find something that you can't use but exists in their documentation, I recommend you check out your ```composer.json``` to see which version of spatie/laravel-permission you're using, then check out the documentation for THAT version.

Hope it helps someone - as late as it is.
Cheers!
