### ISSUE TITLE
Adding fields when creating and updating a user

### ISSUE THREAD

**Issue by kev-ian** [Laravel-Backpack/PermissionManager#18]
Hi

Is there any possibilities to add more fields to the form when creating and updating a user?

Without modifying the vendor files?

**Comment by kev-ian** [comment]
I was able to override the controller and the service provider, the only problem i'm having is how to reorder the input fields being displayed in the create form! Any insight?

**Comment by tabacitu** [comment]
Hi @kev-ian ,

You can actually override the entire UserCrudController. You need to:
- copy it from the package and place it in your app/Http/Controllers/Admin;
- change the namespace to fit your app;
- insert a new route in your web.php route file that overwrites the route set in PermissionManagerServiceProvider:
```php
// inside the 'admin' prefix, I presume
Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
     CRUD::resource('user', 'UserCrudController');
});
```
- make sure in the Backpack routes are loaded before the application routes in your ```app/config.php```, by seeing what order ```App\Providers\RouteServiceProvider::class``` and ```Backpack\PermissionManager\PermissionManagerServiceProvider::class``` are in;

Another way would be instead of copy-paste to create a UserCrudController that extends Backpack's UserCrudController. You'll still need the route though.

Cheers!

PS. For development questions (non-bugs), it's recommended that you post on [Stack Overflow](http://stackoverflow.com/questions/tagged/backpack-for-laravel) (using the ```backpack-for-laravel``` tag) or [Gitter](https://gitter.im/BackpackForLaravel/Lobby), after you're sure you can't solve the problem yourself. There are a lot more people on Gitter and StackOverflow than have notifications for GitHub issues. Plus:
- on StackOverflow people are rewarded with points for helping you out; 
- on StackOverflow your conversation will be better indexed by search engines;
- for super-urgent issues, nothing beats a chatroom, like Gitter; if anyone's online, of course;
- we can keep the Github Issues only for bugs that affect everyone, so we can crush them faster;

If you want to help people out with development question, that would be a [HUGE](https://i.imgflip.com/yuegp.jpg) help for the project. You can answer people:
- synchronously - by leaving your [Gitter app](https://gitter.im/apps) open;
- asynchronously - by [adding a StackOverflow filter](https://stackexchange.com/filters) for the ```backpack-for-laravel``` tag to receive questions by email;
