### ISSUE TITLE
User and BackpackUser models don't have same roles and permissions

### ISSUE THREAD

**Issue by lucasdcrk** [Laravel-Backpack/PermissionManager#183]
# Bug report

The roles assigned on the admin panel (with the BackpackUser model) aren't the same as the User model ones. So the User and BackpackUser models both have different roles and permissions.

![screenshot_202](https://user-images.githubusercontent.com/17224437/50600895-d4488200-0eb2-11e9-84b4-1c800e59918e.png)

### What I did:
Updated to Backpack 1.0, so I now have a separate user model BackpackUser extending my User model

### What I expected to happen:
Nothing

### What happened:
All the users now appear without role in the CRUD, if I add any roles they are saved but they are only applied to the BackpackUser model.

### What I've already tried to fix it:
Made I sure I used
`Tightenco\Parental\HasParentModel;`
in my child model (I do)

### Backpack, Laravel, PHP, DB version:
Backpack 3.5
Laravel 5.7
PHP 7.2
MySQL 8

**Comment by Holonist** [comment]
I made a fresh install of spatie/laravel-permissions and then installed backpack/permissionmanager as per the instructions.

Backpack would use \App\Models\BackpackUser for everything, but the rest of my app was still using \App\User. The spatie roles and permissions middlewares also still used the \App\User model, so administering users in the Backpack frontend had absolutely no consequences in the actual app.

Now, I changed the user models from \App\Models\BackpackUser to \App\User in these files
config/backpack/base.php,
config/backpack/permissionmanager.php

Now the the permission module from spatie works again and using the backpack frontend actually has effects.
But I would like to know why backpack decides to make itself useless out of the box, by not referring to the standard User model

**Comment by mpixelz** [comment]
im using multiple guards as i have 2 different type of users. Users and Admins
everything works fine except i cant get list of admin users with a specific role..
No roles relation is returned for admins. I do have hasRole trait on my admin class.. as well as backpack config file is using backpackUser class with table set as admins.
but i cant seem to get it to work.

anyone here with a solution for multi guard with roles?

**Comment by mpixelz** [comment]
@tabacitu any help on this please?

**Comment by mpixelz** [comment]
solved it.. if anyone else is having the same issue:
instead of using Admin.php (admin user model) i used backpackUser model and it worked.

**Comment by tabacitu** [comment]
@Holonist I think you're right - this might be unnecessarily difficult for new users.

The reason we added BackpackUser is for the Backpack installation process to be automated (since people sometimes move their User model to ```Models\``` or something like that), and to provide a way for people to add functionality only for the admin. When we added ```BackpackUser```, the spatie/laravel-permission package was simpler, and it did NOT store the permissions for a certain model. Or store guards in the database. To be honest - I liked it better back then. When they introduced this, we added support for it but this made it more difficult to use because we had a distinct model.

It seems to me like that was a bad decision, and in v4 we should go back to using ```App\User``` instead of ```App\Models\BackpackUser```. I've added an issue for this here - https://github.com/Laravel-Backpack/Base/issues/399 

The proposed change would move the complexity from the user, to the installation process.

Thanks for taking the time to write here. Let's move the conversation there please.
Cheers!
