### ISSUE TITLE
Looks like PermissionManager isn't compatible with spatie 2.36.x?

### ISSUE THREAD

**Issue by westernstatesflooring** [Laravel-Backpack/PermissionManager#191]
As the title shows, I'm getting an error with installing this package, looks to be requiring a lower version?

  Problem 1
    - backpack/permissionmanager 4.0.1 requires spatie/laravel-permission 2.34.* -> satisfiable by spatie/laravel-permission[2.34.0] but these conflict with your requirements or minimum-stability.
    - backpack/permissionmanager 4.0.0 requires spatie/laravel-permission 2.28.* -> satisfiable by spatie/laravel-permission[2.28, 2.28.1, 2.28.2] but these conflict with your requirements or minimum-stability.
    - Installation request for backpack/permissionmanager ^4.0 -> satisfiable by backpack/permissionmanager[4.0.0, 4.0.1].

**Comment by tabacitu** [comment]
Hi @westernstatesflooring ,

Yes, the version you have installed required a specific version for spatie/laravel-permission (2.34.0), because spatie sometimes release breaking changes as non-breaking. So we wanted to protect users against this. However, since people are installing spatie/laravel-permission separately, before this interface, our previous solution would make it impossible for them to use our package.

So we've bitten the bullet, and are supporting any recent release of spatie/laravel-permission.

You should now be able to install v4.0.4 of this package, which supports spatie/laravel-permission 2.36+

Cheers! Thanks for posting about this.
