### ISSUE TITLE
user role view does not show

### ISSUE THREAD

**Issue by OdaiTu** [Laravel-Backpack/PermissionManager#192]
# Bug report

### What I did:

im using admins table for backpack and its working fine but when i installed the backpack permission manager and config it to use the admin model using this line at 
config/backpack/permissionmanager.php

![image](https://user-images.githubusercontent.com/12837840/55178330-3ce38a00-5196-11e9-97e2-309016203b9e.png)

in my admin model also im using this two lines : 

![image](https://user-images.githubusercontent.com/12837840/55178392-584e9500-5196-11e9-9c6c-3a5c902c24fa.png)

### What I expected to happen:

i expected to view the roles section when trying to add/edit an admin

### What happened:

![image](https://user-images.githubusercontent.com/12837840/55178494-8df37e00-5196-11e9-8841-d05e7219ba4b.png)

### Backpack, Laravel, PHP, DB version:

backpack : 3.5
laravel : 5.7
php : 7.1.3

**Comment by tabacitu** [comment]
Hi @OdaiTu ,

As far as I know, the form will let you pick the roles only after you have roles in the database. Have you added any roles&permissions to the db?

Cheers!

**Comment by OdaiTu** [comment]
Hi @tabacitu 

Yes i did but still no forms

**Comment by shahalpk** [comment]
@OdaiTu can u check if the composer.json have a dependency to `eduardoarandah/usermanager` package.

**Comment by OdaiTu** [comment]
@shahalpk  
no i can not find it at composer.json

**Comment by tabacitu** [comment]
@OdaiTu are you sure you're using the standard  UserCrudController that ships with PermissionManager? Because I see there's another field you're missing here, Password Confirmation.

I've just done the same thing as you, and here's what I see:
![Screenshot 2019-04-25 at 10 37 11](https://user-images.githubusercontent.com/1032474/56717790-1a697000-6746-11e9-9354-4caac467c60e.jpg)

Sounds like you don't have all the ```addField()``` statements for ```password_confirmation``` and ```roles_and_permissions``` in your ```UserCrudController::setup()```. Here's what it should look like:
https://github.com/Laravel-Backpack/PermissionManager/blob/master/src/app/Http/Controllers/UserCrudController.php#L70-L103
