### ISSUE TITLE
How to allow user with a role(non admin) to access a certain page of backpack admin?

### ISSUE THREAD

**Issue by samuk190** [Laravel-Backpack/PermissionManager#203]
I'm using the same guard for backpack admin and user, and verifying if his role is admin to allow access route /admin. (default checkifAdmin function)

But the problem is, I want a certain user to be able access admin/edit-account-info
but restrict for other admin pages.

How I can do it? or better what steps should I take to move the edit-account-info controller to normal auth?

**Comment by tabacitu** [comment]
@samuk190 it's a little tricker, since the ```checkIfAdmin``` middleware is requested inside the ```MyAccountController```.

**Option 1.** Inside ```CheckIfAdmin::checkIfUserIsAdmin()``` you can use ```request()``` to determine if the route is one you want that particular user to have access to, and return true for that user and that route. Seems like a hack though :-)

**Option 2.** Inside your ```config/backpack/base.php``` file, toggle your ```setup_my_account_routes``` to ```false```. This will prevent the routes being loaded. Now add those routes in your ```routes/backpack/custom.php```, BEFORE the default route group: 

```php
Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web'],
    'namespace'  => 'App\Http\Controllers\Admin',
], function () { // custom admin routes
    Route::get('edit-account-info', 'MyAccountController@getAccountInfoForm')->name('backpack.account.info');
    Route::post('edit-account-info', 'MyAccountController@postAccountInfoForm');
    Route::post('change-password', 'MyAccountController@postChangePasswordForm')->name('backpack.account.password');
});
```

They will now point to a new ```app\Http\Controllers\Admin\MyAccountController.php```, that you create, and should extend MyAccountController from the package. This new controller's job would only be to load a different middleware inside ```__construct()```, so you only need to define __construct() inside it and do whatever you want inside it.

Hope it helps.
Cheers!
