### ISSUE TITLE
Please use CrudTrait on the model - error when opening user list

### ISSUE THREAD

**Issue by baschke** [Laravel-Backpack/PermissionManager#219]
# Bug report

### What happened:

Exception
Please use CrudTrait on the model.
http://xxx.xxx.xxx.47:8000/admin/user

### Backpack, Laravel, PHP, DB version: 
Laravel 6.16.0

**Comment by tabacitu** [comment]
Hi @baschke ,

Have you changed the user model inside ```config/backpack/permissionmanager.php```?

**Comment by sokvebolkol** [comment]
Hi @tabacitu, I have change to 
![image](https://user-images.githubusercontent.com/44717892/76594976-1c3e4c80-652d-11ea-92e7-925897e11d22.png)
But still the same error

**Comment by tabacitu** [comment]
Ok, then please make sure you use CrudTrait on your User model, like the error instructs. And like Step 4 from the [installation process](https://github.com/Laravel-Backpack/PermissionManager) of this package instructs.

I'm going to close this as it's not a bug in Backpack. We keep Github for bugs only - your issue is more appropriate for StackOverflow imho - we have quite a few people answering questions there too.

Cheers!
