### ISSUE TITLE
Method assignRole() from HasRole trait not use the default guard

### ISSUE THREAD

**Issue by Sammi89** [Laravel-Backpack/PermissionManager#235]
# Bug report

### What I did:
I'm trying to seed the database. After the creation of the user with Eloquent ::create function (App\User model) I try to assign a role to the user with the assignRole() method from the trait HasRoles.
[Issue.zip](https://github.com/Laravel-Backpack/PermissionManager/files/4628639/Issue.zip)

### What I expected to happen:
I expected that the role will be assigned to the user.

### What happened:
 Spatie\Permission\Exceptions\RoleDoesNotExist: "There is no role named `Administrator`."
The role exits in the database with the guard backpack.

### What I've already tried to fix it:
I check the stack trace of the Exception and found that the method getStoredRole() from HasRoles trait, called from assignRole() use the $this->getDefaultGuardName() to get the default guard name. It return the "web" guard instead of "backpack"guard setted in config/auth.php defaults array.

### Backpack, Laravel, PHP, DB version:
* Laravel 7.11.0
* Backpack 4.1
* PHP 7.2.9
* DB MySql 5.7.24 (x86_64)
* Laragon

**Comment by AbbyJanke** [comment]
The problem seems to be due to your 'guard_name' being 'backpack'. I changed mine to 'web' and it worked.

![Screen Shot 2020-05-17 at 12 19 55 AM](https://user-images.githubusercontent.com/487798/82138293-3ff36c80-97d4-11ea-8ffb-de2463894fb5.png)

Because you are not using the`backpack_user()` to assign the role, it is using what is defined by default with Spatie/Laravel-Permission. which is the default in `config/auth.php` and there is no `guard_name` set in the User Model.

To options to fix this:

1. In your seeder:
```php
        admin = User::create([
            'name' => 'John',
            'email' => 'foo@ffsfdafdsffsdfdfsfafasfsdf.it',
            'password' => bcrypt('jhonfoo'),
        ]);
        $admin->guard_name = 'backpack'; // <!-- Add this
        $admin->assignRole('Manager');
```

2. In your User Model add:
```php
protected $guard_name = 'backpack';
```

It is because it is not being added with backpack so it is not pulling the backpack guard the user is just a plain eloquent record trying using plain Spatie.

**Comment by Sammi89** [comment]
Thank you @AbbyJanke, the fix from point 1 perfectly works.
I added the guard to the **User** model too as you suggested in the second point.
My backpack configuration base file, already contains the `Backpack\Base\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class`
inside the `middleware_class` array.
Thank you very much for this solution.
