### ISSUE TITLE
[Feature Request] Ability to add permission to specific module/model

### ISSUE THREAD

**Issue by lambasoft** [Laravel-Backpack/PermissionManager#249]
I know we can name a permission "view reports", "edit reports", "delete reports". But it would be much cleaner and simpler if we could have a module <-> permission relation, where we can assign a permission to a module/model then assign the combination to a role.

**Comment by tabacitu** [comment]
Hmm I heard people wanting this before. Is that something that spatie/laravel-permission allows? 'Cause this is just an interface for that package.

**Comment by lambasoft** [comment]
@tabacitu Unfortunately not. I have requested the same feature on their repository as well (https://github.com/spatie/laravel-permission/issues/1571)

I'm currently in the process of adding it, I forged both repositories. But it's not an easy task to do solo

**Comment by tabacitu** [comment]
Hmmm... i would't do any work ahead of their reply, if i were you. See if they agree with it first. The way i see it:

1. it would change their package quite a bit, so it would be a breaking change;
2. It would become pretty similar to laravel's policies;

Of course, if they support it we probably will too. If they don't, there's always the option of copy-pasting their code (and our) and adding it in your project only. Or... using laravel policies, which seem very very similar to what you're looking for.


https://laravel.com/docs/8.x/authorization

**Comment by tabacitu** [comment]
Seems like this won't be happening in spatie/laravel-permission so I'm going to close this.

Now that I've slept on it, it doesn't sound like a bad idea to me. It really doesn't. But it doesn't sound like a big benefit _for most projects_ either.

3. Of course, it's just my opinion, but I don't see a lot of benefit in storing "\App\Models\Post" + "create" in the db, rather than storing "post.create".

4. I think it's getting a little too complicated for most projects. I agree it's a reasonable use case, but i get the same feeling as when i  first read about Laravel Policies, imho - perfect for a few really complex projects, but overengineered for most. 

I think most projects just aren't that complex, so giving this level of flexibility to them would not only "not help" but actually make it more difficult to understand and work with.

Hell, for most projects "permissions" aren't really needed at all - just a "roles" layer will do. 

So... yeah. Sorry @lambasoft this didn't pan out the way you wanted, but I think it's for the best. For the software itself, not for you 😅🙄😞
