### ISSUE TITLE
Creating Permissions per Resource

### ISSUE THREAD

**Issue by Sturgelose** [Laravel-Backpack/PermissionManager#25]
Hello,

I've been playing this last weeks with Laravel and Backpack and I can say it's awesome!

I've set up a nice permission system to allow CRUD actions following the great discussion in https://github.com/Laravel-Backpack/PermissionManager/issues/14

However, I'm trying to create something one step away: create permissions allowing to edit a resource and its children resources. That would mean that a resource would kind of have its own set of permissions, and that if I have a 'Group', I could edit all the articles inside an specific group.

Any idea on how I could implement something similar?
I was thinking on create the set of default permissions on the fly, whenever the parent resource is created. And somehow, I think I'll end with Global permissions, and PerResource permissions, plus copying the permission page inside of the resource, for management...

However, I'm a bit lost on where to start :/

Thanks a lot for the hard work!

**Comment by tabacitu** [comment]
Hi @Sturgelose ,

Wooooow :-) Sounds to me like that will easily get out of hand. You're probably going to need to place the permissions directly on the user using a select2, because it can easily get to hundreds/thousands of permissions.

Honestly, I think the simplest solution is the one you proposed: upon creating an entry in the database, you create a new permission. Another, more complicated but more Laravely way to do it would be to create a new table and a [polymorphic relationship](https://laravel.com/docs/5.3/eloquent-relationships#polymorphic-relations) towards all the entities you're giving permission to. But that would make it sooo much more complicated, I think.

I don't recommend going so deep with permissions, though. If you can, get out of it :-)

Cheers!

**Comment by datune** [comment]
I don't think you need to create so many permissions. Just check if the user belongs to the group in question, and if he can edit the type of the resource. So basically like a combined permission. If the user has edit rights for the root resource, he can also edit it's children.

**Comment by lloy0076** [comment]
@datune - that still may fell into the "exponential permission checks" problem.

**Comment by lloy0076** [comment]
PS. Is there any movement on this?

**Comment by tabacitu** [comment]
I think this is a pretty niche use case. As such, I don't think PermissionManager itself should treat it. So closing this issue for the time being. 

Cheers!
