### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by ugintl** [Laravel-Backpack/PermissionManager#283]
If I am using backpack in a project which I am creating for a client, will it be considered commercial use?

**Comment by tabacitu** [comment]
Hi @ugintl . Yes, that's commercial use, since you make money from that project. Buy [one of our commercial licenses](https://backpackforlaravel.com/pricing) in order to use it in production.

On localhost you don't need the license, though. So if you just want to try out Backpack before buying, go ahead, install it, build the admin panel you want. Then when you decide to go to production, purchase the license code.

Hope it helps.
Cheers!

**Comment by ugintl** [comment]
@tabacitu I have a fully functioning app. It has users and login functionality already. Can Backpack generate an admin panel for me? I do not know why but it looks like a myth to me. Is it that simple?

**Comment by ugintl** [comment]
@tabacitu I have a fully functioning app. It has users and login functionality already. Can Backpack generate an admin panel for me? I do not know why but it looks like a myth to me. Is it that simple?

**Comment by tabacitu** [comment]
Yes it can, and it will. Install it on localhost and try it out. Don't expect it to magically be _exactly_ the way you want it, though. You have to tweak the code to make it look & feel how you want (at least change column and field types, use or remove operations, etc). I recommend you [take a look at our video course](https://backpackforlaravel.com/docs/4.1/getting-started-videos), then if you like what you're seeing, try it out.

Cheers!
