### ISSUE TITLE
Role CRUD's List Operation Stopped working.

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/PermissionManager#317]
# Bug report

Role CRUD's List Operation Not working any more.

```SQLSTATE[HY093]: Invalid parameter number (SQL: select count(*) as total_rows from (select `roles`.`id`, (select count(*) from `users` inner join `model_has_roles` on `users`.`id` = `model_has_roles`.`model_id` where `roles`.`id` = `model_has_roles`.`role_id` and `model_has_roles`.`model_type` = ?) as `users_count` from `roles`) as `roles_aggregator`)```

Same Error on BackpackDemo:
[https://demo.backpackforlaravel.com/admin/role](https://demo.backpackforlaravel.com/admin/role)

**Comment by JordanchoEftimov** [comment]
Facing the same issue as well. Really annoying...

**Comment by pxpm** [comment]
Hello guys, thanks for the report. 

That should be fixed in Backpack/CRUD `5.4.11` https://github.com/Laravel-Backpack/CRUD/releases/tag/5.4.11

Please do a `composer show backpack/crud` and make sure you have atleast that version. If not, please update. 

I just confirmed and it's fixed on the master branch: 
![image](https://user-images.githubusercontent.com/7188159/208250846-7727886b-0063-4a8d-878d-3689dbeab02e.png)

Let me know if I missed something 🙏 

Wish you guys the best 🎅

**Comment by tabacitu** [comment]
Ouch! Didn't know that was happening. Crisis averted:
- Pedro's fix in CRUD is merged and tagged, so `composer update` should fix it for everyone;
- I've just run a `composer update` in our demo too, so https://demo.backpackforlaravel.com/admin/role is working again;

Thanks for the heads-up @karandatwani92 , and for pinpointing the issue @JordanchoEftimov .
