### ISSUE TITLE
php artisan migrate, says nothing to migrate

### ISSUE THREAD

**Issue by mcfaith9** [Laravel-Backpack/PermissionManager#322]
# Bug report

### What happened:
Its says nothing to migrate, I dont know why the migration dosent work on the steps i followed.

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'project_teamwork_db.roles' doesn't exist (SQL: select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` in (1, 2) and `model_has_roles`.`model_type` = App\Models\User)

### What I've already tried to fix it:
I just re create db and fresh migrate. 

### Backpack, Laravel, PHP, DB version:
"php": "^7.3|^8.0",
"backpack/crud": "^5.5",
"backpack/permissionmanager": "^6.0",

**Comment by jorgetwgroup** [comment]
Hi @mcfaith9,

Regarding your issue with Backpack, it is possible that the problem is related to your .env file. I recommend double-checking to ensure that your database credentials are correct. If your credentials are correct, you can try running php artisan config:clear to clear any cached configuration files.

If you continue to have issues, please provide us with more information on how you installed Backpack. This information can help us better understand the issue and provide a more accurate solution.

It would be helpful if you could provide a step-by-step explanation of how you installed Backpack. This would include any commands that you ran, any errors that you received, and any other relevant information.

We look forward to hearing back from you and helping to resolve this issue.

**Comment by tabacitu** [comment]
@mcfaith9 sounds to me like you missed a step in the installation procedure. I'm pretty sure you haven't run `php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"`. And yes... if the migration isn't there... it can't be run... so the interface won't work.

**Please go through the [installation steps](https://github.com/Laravel-Backpack/PermissionManager#install) one more time, make sure to run everything.**

If that doesn't solve it for you, dig a little deeper to debug:

(1) Your error says `Table 'project_teamwork_db.roles' doesn't exist`... well ok... why? Does the table _actually_ exist in the db - take a look? I assume it does not.

(2) Is the migration published? Take a look at `database/migrations` - is the roles migration file there? If not... it means you haven't published it... so you gotta run the command again.

Let us know more info, if this doesn't solve it.
Cheers!

**Comment by rkvandervaart** [comment]
Hello,

I had the same issue as [mcfaith9](https://github.com/mcfaith9).
Im on my first laravel project from scratch so if my think process is wrong here, pls let me know.

The issue:
- Base table or view not found: 1146 Table 'dev.permissions' doesn't exist at ...
- Base table or view not found: 1146 Table 'dev.roles' doesn't exist at ...

My install steps (did it 3 times by the installation steps in here to be sure):
```
No security vulnerability advisories found
Using version ^6.0 for backpack/permissionmanager
/var/www/app # php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"

   INFO  No publishable resources for tag [migrations].

/var/www/app # php artisan migrate

   INFO  Nothing to migrate.

/var/www/app # php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"

   INFO  No publishable resources for tag [config].

/var/www/app # php artisan vendor:publish --provider="Backpack\PermissionManager\PermissionManagerServiceProvider" --tag="config" --tag="migrations"

   INFO  Publishing [config] assets.

  Copying directory [/var/www/vendor/backpack/permissionmanager/src/config] to [config] ....................................................... DONE

   INFO  Publishing [migrations] assets.

  Copying directory [/var/www/vendor/backpack/permissionmanager/src/database/migrations] to [database/migrations] ............................. DONE

/var/www/app # php artisan migrate

   INFO  Running migrations.

  2020_03_31_114745_remove_backpackuser_model ............................................................................................. 3ms DONE

/var/www/app # php artisan migrate

   INFO  Nothing to migrate.
```

For me `Spatie\Permission\PermissionServiceProvider` is not creating the local migration files.
If i check in the verdor map, the 2 required migration files are there.

The issue is that the publish tags of `spatie/laravel-permission` changes, if you run:
```
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="permission-config"  --tag="permission-migrations"
```

Then it works:
```
/var/www/app # php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="permission-config"  --tag="permission-migrations"
   INFO  Publishing [permission-config] assets.

  Copying file [/var/www/vendor/spatie/laravel-permission/config/permission.php] to [config/permission.php] ................................... DONE

   INFO  Publishing [permission-migrations] assets.

  Copying file [/var/www/vendor/spatie/laravel-permission/database/migrations/create_permission_tables.php.stub] to [database/migrations/2023_03_25_125123_create_permission_tables.php]  DONE

```

Hope this helps :-D

**Comment by pxpm** [comment]
This was fixed in  https://github.com/Laravel-Backpack/PermissionManager/pull/321

Thanks guys for the help here 🙏 

Cheers
