### ISSUE TITLE
Translate the Roles & Permissions

### ISSUE THREAD

**Issue by alexiswbr** [Laravel-Backpack/PermissionManager#61]
I'm trying to make an entirely translatable site.
So when I create a new role/permission, I have to assign a name, wich is also used to check permissions.

With a french language I get something like this : `$user->hasRole('Développeur')` or `$user->hasPermissionTo('accès backoffice')`

Is there anyway to give to the role/permission a kind of "id name", which will be used in the code but displayed to the user with its translation ?
`$user->hasRole('developer')` or `$user->hasPermissionTo('backoffice_access')`

en : `Your role is "Developer" and you have the following permissions : "Access to the backoffice"`
fr : `Vous avez le rôle de "Développeur" et vous avez les permissions suivantes : "Accès au backoffice"`

And in the backoffice the user will also see the translated roles/permissions name

![screen](https://cloud.githubusercontent.com/assets/15452514/23698144/bba8b19a-03ea-11e7-836c-05af685d07c2.PNG)

**Comment by alexiswbr** [comment]
Is it yet possible and I am missing something or does this repo need some improvement @tabacitu ?

**Comment by flosej** [comment]
Check this out https://laravel-backpack.readme.io/v3.0/docs/advanced-features#section-translatable-models-and-multi-language-cruds

**Comment by lloy0076** [comment]
@alexiswbr - did you investigate the solution proposed in https://github.com/Laravel-Backpack/PermissionManager/issues/61#issuecomment-288993040?

**Comment by alexiswbr** [comment]
Yes I found a solution with SpatieTranslatable. I'll close the issue.
For anyone who can be interested in the future, this is what I did:

I extended the Backpack Role model:
```php
<?php

namespace App\Models;

use Backpack\CRUD\CrudTrait;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\HasTranslations;
use Backpack\PermissionManager\app\Models\Role as OriginalRole;

class Role extends OriginalRole
{
	use HasTranslations;
	use CrudTrait;

	protected $translatable = array('readable_name');

	protected $fillable = ['name', 'readable_name', 'updated_at', 'created_at'];
}
```

I created a Seeder like this:
```php
<?php

use Illuminate\Database\Seeder;
use App\Models\Role;

class UsersRolesPermissionsSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		// ROLES
		$roles = array(
			'dev' => ((new Role(array('name' => 'DEVELOPER')))
				->setTranslation('readable_name', 'fr', 'Développeur')
				->setTranslation('readable_name', 'en', 'Developer')
			),
			'admin' => ((new Role(array('name' => 'ADMIN')))
				->setTranslation('readable_name', 'fr', 'Admin')
				->setTranslation('readable_name', 'en', 'Admin')
			),
		);

		foreach ($roles as $role) {
			$role->save();
		}
	}
}
```

And now I can use the role verification as usual:
```php
if ($user()->hasRole('ADMIN')) {
	echo 'Sweet, access granted!';
}
else {
	echo 'Nop you cant';
}
```

And I made the same thing for the Backpack Permissions model.

**Comment by lecorreyann** [comment]
Sorry for my english. 

I was looking for the same thing after install BackPack and laravel-translatable.

You can do this making two new Models like that : 

- Create new Role Model extending parent Role Model with HasTranslations Trait from Backpack

`<?php

// path : App/Models/Vendor/Backpack/PermissionManager/Role.php

// new Role Model in App/Models/Vendor/Backpack/PermissionManager directory or anything you want and extending parent RoleModel with HasTranslations Trait from Backpack . 

namespace App\Models\Vendor\Backpack\PermissionManager; 
// Be careful about the "as BackpackRoleModel" because if you don't do that laravel can't load with the same class name.
use Backpack\PermissionManager\app\Models\Role as BackpackRoleModel;
use Backpack\CRUD\app\Models\Traits\SpatieTranslatable\HasTranslations;

class Role extends BackpackRoleModel
{
    use HasTranslations;

    protected $translatable = ['name'];
}
`

- and Create new Permission Model extending parent Permission Model with HasTranslations Trait from Backpack

`<?php

// path : App/Models/Vendor/Backpack/PermissionManager/Permission.php

namespace App\Models\Vendor\Backpack\PermissionManager; 

//  Be careful about the "as BackpackPermissionModel" because if you don't do that laravel can't load with the same class name.
use Backpack\PermissionManager\app\Models\Permission as BackpackPermissionModel;
use Backpack\CRUD\app\Models\Traits\SpatieTranslatable\HasTranslations;

class Permission extends BackpackPermissionModel
{
    use HasTranslations;

    protected $translatable = ['name'];
}
`

- And now you have to change something in config file config/backpack/config/permissionmanager.php to help Laravel find your two new Models :)

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Models
    |--------------------------------------------------------------------------
    |
    | Models used in the User, Role and Permission CRUDs.
    |
    */

    'models' => [
        'user'       => App\Models\UserModel::class,
        'permission' => App\Models\Vendor\Backpack\PermissionManager\Permission::class, // change here
        'role'       => App\Models\Vendor\Backpack\PermissionManager\Role::class, // change here
    ],`

Enjoy !

**Comment by tabacitu** [comment]
Thank you for sharing this @lecorreyann !
