### ISSUE TITLE
How to return users who has a certain role in a select field

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/PermissionManager#76]
Hi,

I have a role called 'Center Admin' using PermissionManager.
Now I want to return users who has this role.

At the moment I have followings and it returns all users.
Where can I add `$user->hasRole('Center Admin')`, so that the select field shows only Center admin?

Thanks.

App\User
```
    /**
     * Get the center record associated with the user.
     */
    public function center()
    {
        return $this->hasOne('App\Model\Center');
    }
```

App\Admin\Center
```
    /**
     * Get the user of the center.
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }
```

App\Controller\Admin\CenterController.php
 ```
       $this->crud->addField([
            'name' => 'user_id',
            'label' => 'User',
            'type'=>'select',
            'tab' => 'GENERAL',
            'entity' => 'user', 
            'attribute' => 'name',
            'model'=>'App\User',
        ]);
```

**Comment by tabacitu** [comment]
Hi @shinokada ,

This sounds like a support question, please ask on Stack Overflow. Trying to keep GitHub only for bugs and features, otherwise new development will become very very difficult.

In your SO question please also explain if Center is a Model or a Role - you seem to be using one terminology in your explanation, another in your code.

Closing this. Cheers!

**Comment by shinokada** [comment]
Moved to [Stackoverflow](http://stackoverflow.com/questions/43241878/how-to-return-users-who-has-a-certain-role-in-a-select-field).
Thanks.
